### ISSUE TITLE
[ISSUE] 

### ISSUE THREAD

**Issue by karamzyatina** [TrueMB/DiscordNotify#10]
Good afternoon. When I write the *info command, velocity displays an error in the console: (I attach a screenshot)

The version of the spicord and dinotify plugins is the latest. Velocity version is the latest
![opera_ox1YxaO41s](https://user-images.githubusercontent.com/67735224/187939742-96a03211-6a8c-4a92-b027-dc88793797c6.png)

**Comment by karamzyatina** [comment]
It also spams with errors of this type:
![opera_5YPECK2Z3U](https://user-images.githubusercontent.com/67735224/187939913-3c861375-0d74-4f4b-bc1e-3c505a2f863f.png)

**Comment by TrueMB** [comment]
So you are using velocity correct? Could you send me the whole latest.log?

**Comment by karamzyatina** [comment]
[latest (2).log](https://github.com/TrueMB/DiscordNotify/files/9475290/latest.2.log)

**Comment by TrueMB** [comment]
Weird that the Prefix of the plugin isn't shown. Going to fix that in the future.

Your problem should be the missing/wrong Database Connection:
{MySQL}  Failed to start MySql (Could not create connection to database server. Attempted reconnect 10 times. Giving up.)

**Comment by karamzyatina** [comment]
![opera_pH4oBxOAcB](https://user-images.githubusercontent.com/67735224/188071999-40f1d89b-eb9c-4033-979f-585f4286eb57.png)
![opera_OclmvKPPx4](https://user-images.githubusercontent.com/67735224/188072004-52bdd215-03a9-4dbc-be8c-abdab331071d.png)
Yes, indeed. I specified the wrong password for MySQL, but still the problem remained

**Comment by TrueMB** [comment]
[discordnotify-3.2.2-dev4.zip](https://github.com/TrueMB/DiscordNotify/files/9475410/discordnotify-3.2.2-dev4.zip)

This is a dev Version from my Discord. It should fix the first error. And maybe the second is a follow up. Not sure atm. Please test the version and let me know, if there is still an error.

**Comment by karamzyatina** [comment]
![opera_gud5vqgXNh](https://user-images.githubusercontent.com/67735224/188079432-9de93a2b-ce58-4419-8f44-56f33a547a89.png)

**Comment by karamzyatina** [comment]
You forgot velocity.json

**Comment by karamzyatina** [comment]
![opera_W15OVu98WA](https://user-images.githubusercontent.com/67735224/188079895-151923ba-2ad6-4b3d-ac8b-adef6421c1da.png)
.json, then the error 
![opera_DAo3p5IQji](https://user-images.githubusercontent.com/67735224/188079890-389046b2-5274-43b3-ba77-e5245c1c7ec7.png)
but if you add velocity will still remain

**Comment by TrueMB** [comment]
Sometimes the velocity compiler just doing weird stuff... Thanks for letting me know about the missing JSON.
So the first error disappears, only if the velocity json isn't in the jar? Or did it happen even after that?

Looking into the second error atm.

**Comment by karamzyatina** [comment]
No, if there is no json file, the plugin simply does not start. The server cannot load it and index it, this does not apply to the error at all, you just forgot to add it. I added it myself from the last version of the plugin, it only specifies the path to launch the plugin, you as the creator should know this.

When I launched the DEV version plugin, the errors did not disappear.

Sorry if I put it wrong, I use a translator from Russian to English.

**Comment by TrueMB** [comment]
Yes I know about the velocity.json, otherwise the official version wouldn't have worked :D 
The Velocity Compiler normally should generate a Config from this line: https://github.com/TrueMB/DiscordNotify/blob/4ed0dfda51f8276d6547eca736913584cb1e1c08/src/me/truemb/universal/minecraft/main/VelocityMain.java#L45

But sometimes for some reason, it won't use the correct compiler to generate it. 

I think I need to test it later at home, since my current environment doesn't allow me to test the versions.

**Comment by TrueMB** [comment]
Also, are you using IPv6 to connect to your server?
Which Version of Spicord are you running?
Does the first error appear after you run a command or after joining the server?

**Comment by karamzyatina** [comment]
Also, are you using IPv6 to connect to your server?
Which Version of Spicord are you running?
Does the first error appear after you run a command or after joining the server?

**Comment by karamzyatina** [comment]
No, I don't use IPv6. What is Picard? Yes, the first error in my last message with the screenshots attached to them appears when executing a command via discord.

**Comment by karamzyatina** [comment]
No, I don't use IPv6. What is Picard? Yes, the first error in my last message with the screenshots attached to them appears when executing a command via discord.

**Comment by TrueMB** [comment]
Not Picard, [Spicord ](https://github.com/Spicord/Spicord) :D
This is a dependency, and you should have it installed. At least I saw it once in your log. But the exact Version would be interesting.

Which command are you trying to use through Discord?

**Comment by karamzyatina** [comment]
The latest version of Spicord. The commands are absolutely any, personally I use the *info command for the test. Here is my Spicord config:
![opera_yRqDv2muDo](https://user-images.githubusercontent.com/67735224/188113585-4eb60d04-43b9-41e0-8574-8fe98809b441.png)

((I erased the extra lines of explanation of the #text format so that the entire config fits into 1 screenshot)

**Comment by TrueMB** [comment]
Then this might be an Issue of Spicord itself. It seems to use the Bungeecord Class, even tho it is velocity. I am not sure atm, if this is a problem from my site using the API, or just a bug. Maybe @OopsieWoopsie can tell us something about it.

I will fix the second error later at home.

**Comment by karamzyatina** [comment]
Okay, thanks. I will be waiting for an update. If there are any more questions, I will definitely write to you. Thanks again for the detailed answer and help!

**Comment by anvorgesa** [comment]
The issue with you are having with Spicord is because you are using "snap" and it makes Spicord detect your server as BungeeCord instead of Velocity.

**Comment by karamzyatina** [comment]
Yes, indeed it was related to the snap plugin. Thank you very much! But the second error from the console has not gone anywhere, but the plugin now responds to commands!

**Comment by TrueMB** [comment]
[discordnotify-3.2.2.zip](https://github.com/TrueMB/DiscordNotify/files/9485429/discordnotify-3.2.2.zip)
Could you try this version, if this fixed the error?
