### ISSUE TITLE
[ISSUE] 

### ISSUE THREAD

**Issue by patrikkoudelka** [TrueMB/DiscordNotify#14]
**Describe the bug**
I am getting error after using -verify command, it does not work

**To Reproduce**
1. Restart server
2. Use -verify command
3. See error

**Expected behavior**
--

**Screenshots**
--

**Server (please complete the following information):**
 - Bungeecord/Spigot and the Version: [e.g. Spigot 17.1] Velocity
 - DiscordNotify Plugin Version The newest one
 - Plugins on the Server ---

**Additional context**
https://pastebin.com/PqN9nFjk

**Comment by TrueMB** [comment]
Sorry for the late response. I thought I answered it already.
But if I see it correctly, then you already got your answer.
For anybody else wondering:
![grafik](https://github.com/TrueMB/DiscordNotify/assets/25579052/3f048e7c-fa99-41e3-aa0b-0d6e0591fa46)

**Comment by patrikkoudelka** [comment]
Hello, this was solved. Thank you!
