### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by ruk13xa** [TrueMB/DiscordNotify#19]
I think it will be good if 
```messageFormat: '[discord] &6%username% >> %message%'```
this stuff is possible in Options.Broadcast
so it will show like 
[discord] TrueMB >> hi

**Comment by TrueMB** [comment]
Added https://github.com/TrueMB/DiscordNotify/commit/06c3838f4abf9c49309917a921d69096fe56d7dd

Dev Build can be downloaded here: https://github.com/TrueMB/DiscordNotify/actions/runs/8039250683/artifacts/1273265113
