### ISSUE TITLE
[ISSUE] cant verify user

### ISSUE THREAD

**Issue by SevensRequiem** [TrueMB/DiscordNotify#22]
requiem.moe — Today at 12:38 AM
+verify
-verify
Shutcraft🍉
APP
 — Today at 12:38 AM
Please use /verify <IngameName>
requiem.moe — Today at 12:39 AM
-verify reqmoe
Shutcraft🍉
APP
 — Today at 12:39 AM
You are already authenticated. Please use -verify unlink to reset the linking.
requiem.moe — Today at 12:39 AM
-verify unlink
Shutcraft🍉
APP
 — Today at 12:39 AM
You are not Verified.

**Comment by TrueMB** [comment]
Did you set up the verification Role?
https://wiki.uc-gg.de/en/DiscordNotify/Configuration#verification

**Comment by SevensRequiem** [comment]
I did, it does not work with role id's? I cant use the name itself because the name itself has some emojis

**Comment by TrueMB** [comment]
Should work both. Then I need the latest.log from the Proxy that includes a verification process.

**Comment by SevensRequiem** [comment]
INFO
17:51:04

Registered addon 'Player List' (spicord::players) by Tini
Registered addon 'Disnotify PlayerInfo' (disnotify::playerinfo) by TrueMB
Registered addon 'Disnotify Verify' (disnotify::verify) by TrueMB
Starting the bots...
Starting bot 'default'.
[DEBUG]: Changed JDA Status [INITIALIZING -> INITIALIZED]
[DEBUG]: Changed JDA Status [INITIALIZED -> LOGGING_IN]

17:51:05

Login Successful!
[DEBUG]: Changed JDA Status [LOGGING_IN -> CONNECTING_TO_WEBSOCKET]
Connected to WebSocket
[DEBUG]: Changed JDA Status [CONNECTING_TO_WEBSOCKET -> IDENTIFYING_SESSION]
[DEBUG]: Changed JDA Status [IDENTIFYING_SESSION -> AWAITING_LOGIN_CONFIRMATION]

17:51:06

[DEBUG]: Changed JDA Status [AWAITING_LOGIN_CONFIRMATION -> LOADING_SUBSYSTEMS]

17:51:07

Finished Loading!
[DEBUG]: Changed JDA Status [LOADING_SUBSYSTEMS -> CONNECTED]
[DEBUG]: Cleaning up commands for bot default
Logged in as Shutcraft ? ?#9268 (id: 1123398625221935205)
Available Guilds:
- shut-in network ? (id: 895738895931670558)
Loading all Chat/Staff Channel Id's.
Chat/Staff Channel Id's are found.
Connected with Discord BOT.
[DEBUG]: Registered discord command /info
[DEBUG]: Registered discord command /players

17:51:08

[DEBUG]: Registered discord command /plugins


[connected player]: reqmoe (/) has connected
[server connection]: reqmoe -> lobby has connected

17:51:30

[connected player]: reqmoe (/1) -> executed command /verify

17:51:32

[connected player]: reqmoe (/xxxxx1) -> executed command /verify accept

17:52:53

[connected player]: reqmoe (/1) -> executed command /sp status

![image](https://github.com/user-attachments/assets/90899274-3816-472d-9257-cc390d2e0258)
I have the role that is set to be allowed verification via roleid

**Comment by TrueMB** [comment]
Did you set up 'DiscordCommandAllowedGroups'?
![grafik](https://github.com/user-attachments/assets/a7e0a167-8d4d-43dc-9b96-0b1a56bab33c)

If yes, then this group is needed by the users on the discord Server. And it seems, thats not the case.
