### ISSUE TITLE
[ISSUE] UpdateChecker repository

### ISSUE THREAD

**Issue by mfnalex** [TrueMB/DiscordNotify#6]
Hi, I just saw that you still have my old repository URL in your pom.xml (repo.jeff-media.de). You probably already know this, but: the repository URL changed months ago to https://hub.jeff-media.com/nexus/repository/jeff-media-public/ :) (just wanted to mention this)

**Comment by TrueMB** [comment]
Thatswhy I opened the Issue on your Page :D 

Yea, working currently on updates of my repository, since my local one completly died on me. Will be updated shortly ^^

**Comment by TrueMB** [comment]
Updated in 4ee3aee995d946162ee754367cb06f1f0f1e74a7
